import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/component/NavBar";
import Footer from "@/component/Footer";

export const metadata: Metadata = {
  title: "Zoftmo Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-[POPPINS-REGULAR]"
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
